### ISSUE TITLE
Extbase arguments are not respected in topwire rendered plugins if routes are used

### ISSUE THREAD

**Issue by sascha-egerer** [topwire/topwire#36]
Extbase arguments are not properly used once a plugin is rendered using `<topwire:context.plugin />` with `<topwire:context.render />`.

Example TypoScript:
```
page  {
 ...
# with topwire
 10 = FLUIDTEMPLATE
 10.templateRootPaths.10 = EXT:xxx/Resources/Private/Templates/
 10.templateName = Test.html

# without topwire
  20 < tt_content.list.20.foo_thepluign
}
```

Test.html
```
<html xmlns:topwire="http://typo3.org/ns/Topwire/ViewHelpers" data-namespace-typo3-fluid="true">
    <topwire:context.plugin extensionName="myext" pluginName="theplugin" action="something">
        <topwire:context.render />
    </topwire:context.plugin>
</html>
```

ThePluginController.php
```
    ...
        public function somethingAction(?string $myArgument = null): ResponseInterface {
             dump($myArgument)
        }
     ...
```

```
routeEnhancers:
    Foo:
        type: Extbase
        extension: Foo
        plugin: thePlugin
        defaultController: 'ThePlugin::something'
        routes:
            -   routePath: '/extbase-route-{myargument}'
                _controller: 'ThePlugin::something'
                _arguments:
                    myargument: myArgument
        aspects:
            myArgument:
                type: StaticValueMapper
                map:
                    abc: 'abc'
                    xyz: 'xyz'
```

Example URL
https://site.tld/?tx_foo_theplugin%5Baction%5D=something&tx_foo_theplugin%5Bcontroller%5D=ThePlugin&tx_foo_theplugin%5BmyArgument%5D=abc

Output:
```
abc
abc
```

Example URL
https://site.tld/extbase-route-abc

Output:
```
null
abc
```
